#!/usr/bin/env python3
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
TASK_RUNS_DIR = REPO_ROOT / 'runtime' / 'task_runs'
OUTPUT_DIR = Path(__file__).resolve().parent
JSON_PATH = OUTPUT_DIR / 'task_run_index.json'
HTML_PATH = OUTPUT_DIR / 'task_run_index.html'


def load_verification_status(path: Path) -> str:
    if not path.exists():
        return 'unknown'
    try:
        data = json.loads(path.read_text())
    except Exception:
        return 'unknown'
    status = data.get('verification_status', 'unknown')
    return status if isinstance(status, str) and status else 'unknown'


def load_completion_claim_allowed(path: Path, verification_status: str) -> bool:
    if not path.exists():
        return False
    try:
        data = json.loads(path.read_text())
    except Exception:
        return verification_status == 'passed'
    if verification_status != 'passed':
        return False
    return data.get('verification_status') == 'passed'


def build_tasks():
    tasks = []
    for task_dir in sorted([p for p in TASK_RUNS_DIR.iterdir() if p.is_dir()]):
        preflight = task_dir / 'preflight.md'
        task_run_record = task_dir / 'task_run_record.md'
        verification_record = task_dir / 'verification_record.json'
        final_checklist = task_dir / 'final_response_checklist.md'
        verification_status = load_verification_status(verification_record)
        completion_claim_allowed = load_completion_claim_allowed(verification_record, verification_status)
        tasks.append({
            'task_id': task_dir.name,
            'has_preflight': preflight.exists(),
            'has_task_run_record': task_run_record.exists(),
            'has_verification_record': verification_record.exists(),
            'has_final_response_checklist': final_checklist.exists(),
            'verification_status': verification_status,
            'completion_claim_allowed': completion_claim_allowed,
        })
    return tasks


def render_html(index_data):
    rows = []
    for task in index_data['tasks']:
        rows.append(f"""
        <tr>
          <td><code>{task['task_id']}</code></td>
          <td>{'yes' if task['has_preflight'] else 'no'}</td>
          <td>{'yes' if task['has_task_run_record'] else 'no'}</td>
          <td>{'yes' if task['has_verification_record'] else 'no'}</td>
          <td>{'yes' if task['has_final_response_checklist'] else 'no'}</td>
          <td><span class=\"status status-{task['verification_status']}\">{task['verification_status']}</span></td>
          <td>{'yes' if task['completion_claim_allowed'] else 'no'}</td>
        </tr>
        """)
    rows_html = ''.join(rows)
    total = len(index_data['tasks'])
    return f"""<!DOCTYPE html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
  <title>Task Run Index</title>
  <style>
    :root {{ color-scheme: dark; }}
    body {{ background: #0f172a; color: #e2e8f0; font-family: Arial, sans-serif; margin: 0; padding: 32px; }}
    .wrap {{ max-width: 1120px; margin: 0 auto; }}
    .panel {{ background: #111827; border: 1px solid #334155; border-radius: 14px; padding: 20px; margin-bottom: 20px; }}
    h1, h2 {{ margin-top: 0; }}
    ul {{ margin: 8px 0 0 20px; }}
    table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
    th, td {{ border-bottom: 1px solid #334155; padding: 10px 12px; text-align: left; vertical-align: top; }}
    th {{ color: #93c5fd; }}
    .status {{ display: inline-block; border-radius: 999px; padding: 4px 10px; font-size: 12px; font-weight: 700; text-transform: uppercase; }}
    .status-passed {{ background: #14532d; color: #bbf7d0; }}
    .status-partial {{ background: #78350f; color: #fde68a; }}
    .status-failed {{ background: #7f1d1d; color: #fecaca; }}
    .status-unknown {{ background: #1e293b; color: #cbd5e1; }}
    .warning {{ color: #fca5a5; font-weight: 700; }}
    code {{ color: #bfdbfe; }}
  </style>
</head>
<body>
  <div class=\"wrap\">
    <div class=\"panel\">
      <h1>Task Run Auto-Index</h1>
      <p class=\"warning\">This page is generated from local task-run records.</p>
      <p class=\"warning\">It is viewer-only.</p>
      <p>It does not execute actions.</p>
      <p>It does not approve actions.</p>
      <p>It does not mutate memory.</p>
      <p>It does not write to external knowledge store.</p>
      <p>It does not touch upstream private runtime.</p>
    </div>
    <div class=\"panel\">
      <h2>Summary</h2>
      <p>Total task count: <strong>{total}</strong></p>
      <p>Generated by: <code>{index_data['generated_by']}</code></p>
      <p>Viewer mode: <code>{index_data['viewer_mode']}</code></p>
      <p>Actor permissions: <code>{str(index_data['actor_permissions']).lower()}</code></p>
    </div>
    <div class=\"panel\">
      <h2>Indexed Task Runs</h2>
      <table>
        <thead>
          <tr>
            <th>Task ID</th>
            <th>Has preflight?</th>
            <th>Has task record?</th>
            <th>Has verification?</th>
            <th>Has final checklist?</th>
            <th>Verification status</th>
            <th>Completion claim allowed?</th>
          </tr>
        </thead>
        <tbody>
          {rows_html}
        </tbody>
      </table>
    </div>
  </div>
</body>
</html>
"""


def main():
    tasks = build_tasks()
    index_data = {
        'viewer_mode': 'viewer_only',
        'actor_permissions': False,
        'generated_by': 'generate_task_index.py',
        'tasks': tasks,
    }
    JSON_PATH.write_text(json.dumps(index_data, indent=2) + '\n')
    HTML_PATH.write_text(render_html(index_data))
    print(json.dumps({'generated': True, 'task_count': len(tasks), 'json': str(JSON_PATH), 'html': str(HTML_PATH)}))


if __name__ == '__main__':
    main()
